# Generated by Django 2.1.3 on 2018-11-30 17:06

import ASP_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicDistances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('currentClinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentDroneClinic', to='users.Clinic')),
                ('nextClinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextDestinationClinic', to='users.Clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('droneID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
                ('shippingWeight', models.FloatField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to=ASP_app.models.get_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')])),
                ('status', models.CharField(blank=True, choices=[('Queued for Processing', 'Queued for Processing'), ('Processing by Warehouse', 'Processing by Warehouse'), ('Queued for Dispatch', 'Queued for Dispatch'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], max_length=256)),
                ('orderTime', models.DateTimeField(auto_now_add=True)),
                ('dispatchTime', models.DateTimeField(blank=True, null=True)),
                ('deliveryTime', models.DateTimeField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Clinic')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASP_app.Medicine')),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASP_app.Order')),
            ],
        ),
        migrations.AddField(
            model_name='dispatch',
            name='orderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASP_app.Order'),
        ),
    ]
